import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@style/global.css";
import * as style from "@style/home/main.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className={style.main_layout_container}>{children}</div>
      </body>
    </html>
  );
}
