import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@style/global.css";
import * as style from "@style/home/main.css";
import Header from "./(home)/(components)/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${inter.className} ${style.scroll_hidden}`}>
        <div className={style.main_layout_container}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
